# Generated by Django 4.2.7 on 2023-11-16 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format: +999999999,  Up to 15 digits max.', regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('avatar', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
